#
# Copyright (c) 2019 Diego Asanza
# 
# SPDX-License-Identifier: Apache License 2.0
# 
# Created Date: Saturday May 25th 2019
# Author: Diego Asanza
#

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

if(MINGW OR CYGWIN OR WIN32)
	set(EXECUTABLE_FILE_EXTESION .exe)
endif()

set(TOOLCHAIN_PREFIX arm-none-eabi-)

find_path(BINUTILS_PATH ${TOOLCHAIN_PREFIX}gcc${EXECUTABLE_FILE_EXTESION})

SET (CMAKE_C_COMPILER_WORKS 1)

set(CMAKE_C_COMPILER ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}gcc${EXECUTABLE_FILE_EXTESION} CACHE INTERNAL "c compiler")
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER} CACHE INTERNAL "asm compiler")
set(CMAKE_CXX_COMPILER ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}g++${EXECUTABLE_FILE_EXTESION} CACHE INTERNAL "c++ compiler")

set(CMAKE_OBJCOPY ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
